### ISSUE TITLE
Cant launcher

### ISSUE THREAD

**Issue by Cicodevada** [AlphaBs/pml#5]
`Traceback (most recent call last):
  File "launcher.py", line 48, in <module>
    screen_height=0)
  File "C:\teste\pmlauncher\pml.py", line 41, in startProfile
    downloadProfile(profile)
  File "C:\teste\pmlauncher\pml.py", line 36, in downloadProfile
    downloader.downloadAll(downloadAssets)
  File "C:\teste\pmlauncher\mdownloader.py", line 65, in downloadAll
    self.downloadResources()
  File "C:\teste\pmlauncher\mdownloader.py", line 89, in downloadResources
    content = f.read()
  File "C:\Users\Cico\AppData\Local\Programs\Python\Python36\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 13: character maps to <undefined>`

Give-me this error :(

**Comment by Cicodevada** [comment]
![image](https://user-images.githubusercontent.com/41352672/209882348-67f173c5-c4b9-4183-99ea-a9f0d1c7944c.png)
